### PR TITLE
Add designs and animations

### PR DESCRIPTION
**Pull request by uch1**
I implemented the designs and animations in Swift. I created separated methods to handle UI constraints, and these methods exist in the UIView extension.

### CODE REVIEW

**Comment by LinnierGames** [comment]
@uch1 I believe you still have **merge conflicts** between `dev` and your branch.

**Please execute the following in your terminal**:
1. `git checkout dev`
1. `git fetch`
1. `git merge`
1. `git checkout uchenna-scanVC`
1. `git merge dev`
1. `atom .` use Atom to fix the merge conflicts. I suggest consulting @yveslym if you need help fixing the conflicts to reduce losing needed code.

**Comment by yveslym** [comment]
i just solve the merge conflict, @LinnierGames you can check it out and merge with dev, if everything is good

**Comment by LinnierGames** [comment]
@yveslym can I ask what was the reason for **updating this branch with yours?** Was the changes from you branch tied to this feature branch?

**Review by LinnierGames — COMMENTED** [review]
Looks good, thanks for fixing the merge conflicts

**Review by LinnierGames — APPROVED** [review]
Looks good

**Comment by yveslym** [comment]
Yes, at first when I've fixed the merge conflict, i didn't realized that some code was put together, which shouldn't happen, then i had to fix it and make it run, but i realized again that the junk code from the pod was interfering with the app, so i had to clean it up as well and make it run all code from uchenna branch and mine (which come from the dev branch). now all works

**Review by yveslym — APPROVED** [review]
all works for the best.

**Pull request merged**
