### PR TITLE
Uchenna student dashboard

### PR DESCRIPTION
**Pull request by yveslym**
this version is ready to go to the test flight.
Attendance in and out with local notification work.
Dashboard with student project display work as well

### CODE REVIEW

**Comment by yveslym** [comment]
Duncan you can review

**Review by oct0f1sh — APPROVED** [review]
Great job, guys!

**Review by uch1 — APPROVED** [review]
Good to go on TestFlight

**Comment by uch1** [comment]
Add to TestFlight

**Pull request merged**
